# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
permalink:        pretty

# Setup
title:            Unnikked
tagline:          '- Esperienze personali in campo informatico'
description:      'Esperienze personali in campo informatico by <a href="https://twitter.com/unnikked">Nicola Malizia'
url:              https://unnikked.tk

author:
  name:           'Nicola Malizia'
  url:            https://twitter.com/unnikked

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

#Google Analytics
google-analytics: true
ga-id: "UA-36754539-1"
