# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Unnikked
tagline:          'esperienze personali in campo informatico'
description:      'esperienze personali in campo informatico'
name: unnikked
baseurl:          /

author:
  name:           'Nicola Malizia'
  url:            https://twitter.com/unnikked

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/unnikked
